BROKER_URL = "redis://[redis host name]"
CELERY_ANNOTATIONS = {"*": {"rate_limit": "100/h"}}
CELERY_RESULT_BACKEND = "redis://[celery backend]"
APP_KEY = 'Sina weibo API KEY'
APP_SECRET = 'Sina weibo APP SECRET'
CALLBACK_URL = 'http://[Sina callback url]'
WEIBO_ACCOUNT = 'youraccount email'
WEIBO_PASSWORD = 'your password'
MONGO_SERVER = 'mongo db server'